apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-ui
spec:
  replicas: 2
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: sujata-app
  template:
    metadata:
      labels:
        app: sujata-app
    spec:
      containers:
      - image: sujataprjena/applogclientmetric:1.0
        name: sujata-app
        ports:
        - containerPort: 80
